version: "2"

build:
  os: ubuntu-lts-latest
  tools:
    python: "latest"
  jobs:
    pre_build:
      - cd docs && python generate_api_rst.py
      - cd docs && wget https://hg.reportlab.com/hg-public/reportlab/raw-file/tip/CHANGES.md


sphinx:
  configuration: docs/conf.py

  
python:
  install:
    - requirements: requirements.txt
