name: CI

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  docs:
    name: Check docs build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: '3.x'
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Generate API source file
      run: |
        cd docs && python generate_api_rst.py
    - name: Download changelog
      run: |
        cd docs && wget https://hg.reportlab.com/hg-public/reportlab/raw-file/tip/CHANGES.md
    - name: Test docs build
      run: |
        python -m sphinx -T -b html -d _build/doctrees -D language=en docs _build/html
